---
name: BigModel/Zhipu AI Integration

"on":
  workflow_dispatch:
    inputs:
      task_type:
        description: 'Task type (code, deep, review, chat)'
        required: true
        default: 'code'
        type: choice
        options:
          - code
          - deep
          - review
          - chat
      messages:
        description: 'Messages in JSON format'
        required: true
        type: string
      temperature:
        description: 'Temperature for AI response (0.0-1.0)'
        required: false
        default: '0.2'
        type: string
  push:
    branches:
      - main
    paths:
      - 'scripts/bigmodel-zhipu-integration.py'
  pull_request:
    branches:
      - main
    paths:
      - 'scripts/bigmodel-zhipu-integration.py'

permissions:
  contents: read
  actions: write

env:
  BIGMODEL_MODEL: ${{ secrets.BIGMODEL_MODEL || 'glm-4' }}
  ZHIPU_MODEL: ${{ secrets.ZHIPU_MODEL || 'glm-4-9b-code' }}
  BIGMODEL_ENDPOINT: >-
    ${{ secrets.BIGMODEL_ENDPOINT ||
    'https://open.bigmodel.cn/api/paas/v4/chat/completions' }}
  MAX_TOKENS_PER_CALL: ${{ secrets.MAX_TOKENS_PER_CALL || '1200' }}
  MAX_DAILY_CALLS: ${{ secrets.MAX_DAILY_CALLS || '500' }}
  ROUTE_THRESHOLD_CHARS: ${{ secrets.ROUTE_THRESHOLD_CHARS || '8000' }}

jobs:
  bigmodel-zhipu-integration:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Validate script exists
        run: |
          if [ ! -f ./scripts/bigmodel-zhipu-integration.py ]; then
            echo "Missing scripts/bigmodel-zhipu-integration.py" >&2
            exit 2
          fi
          chmod +x ./scripts/bigmodel-zhipu-integration.py

      - name: Test BigModel/Zhipu integration (workflow dispatch)
        if: github.event_name == 'workflow_dispatch'
        env:
          BIGMODEL: ${{ secrets.BIGMODEL }}
          ZHIPU: ${{ secrets.ZHIPU }}
          STATE_DIR: './.glm-companion/workspace'
        run: |
          # Create test payload from workflow inputs
          echo '{
            "task_type": "${{ github.event.inputs.task_type }}",
            "messages": ${{ github.event.inputs.messages }},
            "temperature": ${{ github.event.inputs.temperature }}
          }' | python ./scripts/bigmodel-zhipu-integration.py

      - name: Test BigModel/Zhipu integration (code review)
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        env:
          BIGMODEL: ${{ secrets.BIGMODEL }}
          ZHIPU: ${{ secrets.ZHIPU }}
          STATE_DIR: './.glm-companion/workspace'
        run: |
          # Get changed files for code review
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            CHANGED_FILES=$(git diff --name-only \
              origin/main...HEAD | head -5)
          else
            CHANGED_FILES=$(git diff --name-only \
              HEAD~1 HEAD | head -5)
          fi

          if [ -z "$CHANGED_FILES" ]; then
            echo "No changed files to review"
            exit 0
          fi

          # Create code review payload
          echo '{
            "task_type": "code",
            "messages": [
              {
                "role": "system",
                "content": >-
                  You are a code reviewer. Analyze the provided
                  code changes and provide feedback.
              },
              {
                "role": "user",
                "content": >-
                  Please review these changed files: '"$CHANGED_FILES"'
              }
            ],
            "temperature": 0.2
          }' | python ./scripts/bigmodel-zhipu-integration.py

      - name: Upload artifacts (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bigmodel-zhipu-output
          path: ./.glm-companion/workspace/
          if-no-files-found: ignore
