name: Gemini

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  deduplicate-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout spiralgang/UBULITE
        uses: actions/checkout@v4
        with:
          repository: spiralgang/UBULITE   # target repo UBULITE
          fetch-depth: 0

      - name: Set up GitHub CLI
        uses: cli/cli-action@v4

      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Ensure gemini PRs
        env:
          GH_TOKEN: ${{ secrets.GEMINI }}   # secret: GEMINI
          BRANCH_NAME: ${{ github.ref_name }}   # branch: main
          BASE_BRANCH: main
        run: |
          set -euo pipefail
          echo "🔒 Running Gemini dedupe on ${BRANCH_NAME} → ${BASE_BRANCH}"
          EXISTING_PR=$(gh pr list \
            --repo spiralgang/UBULITE \
            --state open \
            --head "$BRANCH_NAME" \
            --base "$BASE_BRANCH" \
            --json number \
            --jq '.[0].number' || echo "")

          if [[ -n "$EXISTING_PR" ]]; then
            echo "🔄 PR #$EXISTING_PR exists. Pushing updates..."
            git push origin "$BRANCH_NAME"
            gh pr comment "$EXISTING_PR" \
              --repo spiralgang/UBULITE \
              --body "Branch \`$BRANCH_NAME\` updated by automation. No duplicate PR opened."
          else
            echo "🚀 Creating PR: $BRANCH_NAME → $BASE_BRANCH"
            gh pr create \
              --repo spiralgang/UBULITE \
              --title "Automated Gemini Fix: $BRANCH_NAME → $BASE_BRANCH" \
              --body "Automated PR created by Gemini. See workflow logs for details." \
              --base "$BASE_BRANCH" \
              --head "$BRANCH_NAME"
          fi

      - name: Log completion
        run: echo "✅ Copilot deduplication complete."
