name: Gemini AI Review (High-level)

# High-level intent:
# - Run a robust, production-oriented Gemini Pro 2.5 code review pipeline (explicitly disallowing "flash" variants).
# - Provide configurable behavior via environment variables / repo secrets.
# - Produce machine-readable review artifacts and optionally post a summary back to the PR.
# - Designed for code-quality, security, correctness, performance, and test coverage guidance.
#
# Key design choices (traceable):
# - Full repo fetch (fetch-depth: 0) so diffs can be computed reliably in CI.
# - Minimal required permissions by default; elevate to write only when POST_BACK=true to limit blast radius.
# - Secrets are required for Gemini endpoint & key; workflow does NOT hardcode endpoints/keys.
# - Output artifacts are stored as workflow artifacts and printed to logs for auditability.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write  # required only if POST_BACK=true; we use token conditionally

jobs:
  gemini-review:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Ensure script is present (fail fast if not)
        run: |
          if [ ! -f ./scripts/ai-review/gemini-review.js ]; then
            echo "Missing scripts/ai-review/gemini-review.js" >&2
            exit 2
          fi
          chmod +x ./scripts/ai-review/gemini-review.js

      - name: Run Gemini Pro 2.5 review (high-level)
        id: run_review
        env:
          GEMINI_API_ENDPOINT: ${{ secrets.GEMINI_API_ENDPOINT }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: "gemini-pro-2.5"
          REVIEWERS: "Gemini Pro 2.5 (high-level)"
          STANDARDS: "vault"
          POST_BACK: ${{ secrets.GEMINI_POST_BACK || 'false' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI_COMMIT_SHA: ${{ github.sha }}
          CI_PR_NUMBER: ${{ github.event.pull_request.number || '' }}
        run: |
          node ./scripts/ai-review/gemini-review.js

      - name: Upload review artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gemini-review-output
          path: ./artifacts/gemini-review-*.json